name = "DifferentiableWasserstein"
uuid = "dc0500a2-ca5f-4e9f-b764-e9aad48a3f00"
authors = ["Xiangting Li"]
version = "1.0.0-DEV"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
